name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    
    - name: Build
      run: |
        cd StompCoin-macOS
        swift build
    
    - name: Run Tests
      run: |
        cd StompCoin-macOS
        swift test
    
    - name: Check Formatting
      run: |
        cd StompCoin-macOS
        swift format --check . 